version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/node_api
      PORT: 3333
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres_node_api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: node_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: