version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "3333:3333" # Porta do backend
    environment:
      DATABASE_URL:  ${DATABASE_URL}
      PORT: 3333
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000" # Porta do frontend
    environment:
      NEXT_PUBLIC_API_URL: ${BACKEND_URL} # URL do backend
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: postgres_node_api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: node_api
    ports:
      - "5433:5432" # Porta do banco de dados
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: