version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333" # Porta do backend
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_Wl2QRYkz3FtX@ep-old-darkness-advb6utu-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      PORT: 3333
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Porta do frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3333 # URL do backend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    container_name: postgres_node_api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: node_api
    ports:
      - "5433:5432" # Porta do banco de dados
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: