POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video asasas",
  "description": "This is tais video.",
  "duration": 240
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/055edb5f-1ef2-4118-8275-9bb2c364feb0
Content-Type: application/json

{
  "title": "Video novo",
  "description": "This is another video.",
  "duration": 240
}


###

DELETE  http://localhost:3333/videos/055edb5f-1ef2-4118-8275-9bb2c364feb0